version: "3.9"

networks:
  web:
    external: false

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/dynamic
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --api=true
      # Let's Encrypt (HTTP-01)
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - ./traefik/dynamic:/dynamic:ro
    networks: [web]
    labels:
      - traefik.enable=true

      # Redirect http -> https
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      # Dashboard (BasicAuth)
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=dashboard-auth@file

  n8n:
    build:
      context: ./n8n
      dockerfile: Dockerfile
    container_name: n8n
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${N8N_HOST}/
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=true
      - DB_TYPE=sqlite
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_LOG_LEVEL=info
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    networks: [web]
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=le
      - traefik.http.services.n8n.loadbalancer.server.port=5678

  metamcp-db:
    image: postgres:16-alpine
    container_name: metamcp-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=metamcp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${METAMCP_PG_PASSWORD}
    volumes:
      - metamcp_pg_data:/var/lib/postgresql/data
    networks: [web]

  metamcp:
    image: ghcr.io/metatool-ai/metamcp:2.4.13
    container_name: metamcp
    restart: unless-stopped
    depends_on:
      - metamcp-db
    environment:
      # URL pública (CORS/SSE): debe coincidir con la URL usada por los clientes
      - APP_URL=https://${MCP_HOST}
      # Conexión a Postgres
      - DATABASE_URL=postgresql://postgres:${METAMCP_PG_PASSWORD}@metamcp-db:5432/metamcp
      # Secrets de la app
      - BETTER_AUTH_SECRET=${METAMCP_BETTER_AUTH_SECRET}
      - ENCRYPTION_KEY=${METAMCP_ENCRYPTION_KEY}
      # Puerto interno
      - PORT=12008
    networks: [web]
    labels:
      - traefik.enable=true
      - traefik.http.routers.mcp.rule=Host(`${MCP_HOST}`)
      - traefik.http.routers.mcp.entrypoints=websecure
      - traefik.http.routers.mcp.tls.certresolver=le
      - traefik.http.services.mcp.loadbalancer.server.port=12008
      # SSE: timeouts amplios + CORS
      - traefik.http.services.mcp.loadbalancer.serverstransport=sse@file
      - traefik.http.routers.mcp.middlewares=mcp-cors@file

volumes:
  traefik_letsencrypt:
  n8n_data:
  n8n_files:
  metamcp_pg_data:
