version: "3.9"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=true
      - DB_TYPE=sqlite
      # - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      # - DB_SQLITE_BUSY_TIMEOUT=3000
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_LOG_LEVEL=info
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    healthcheck:
      test: ["CMD", "node", "-e", "http=require('http');http.get('http://localhost:5678/',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  n8n_data:
  n8n_files:
