http:
  middlewares:
    dashboard-auth:
      basicAuth:
        # Cambia el hash por el tuyo (htpasswd -nb admin 'MiClave123')
        users:
          - "admin:$apr1$IQZ7dOnd$3ykLfuq6FEcuZFA1zUsSx0"
    mcp-cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowCredentials: false
        accessControlAllowHeaders:
          - "*"
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
        customResponseHeaders:
          X-Accel-Buffering: "no"
          Cache-Control: "no-cache"
